logs:
  - name: root
    level: INFO
    formatter: "%d{%Y-%m-%d %H:%M:%S}%T[%t %N]%T%T[%p]%T[%c]%T%f:%l%T%m%T%n"
    appenders:
      # - type: FileLogAppender
      #   file: root_log.txt
      - type: StdoutLogAppender
  - name: system
    level: ERROR
    formatter: "%d{%Y-%m-%d %H:%M:%S}%T[%t %N]%T%T[%p]%T[%c]%T%f:%l%T%m%T%n"
    appenders:
      # - type: FileLogAppender
      #   file: system_log.txt
      - type: StdoutLogAppender

tcp:
  msg_queue_size: 5
  # netif_in_queue_size: 5
  # netif_out_queue_size: 5

arp:
  # arp_cache_size: 100
