logs:
  - name: root
    level: INFO
    formatter: "%d{%Y-%m-%d %H:%M:%S}%T[%t %N]%T%F%T[%p]%T[%c]%T%f:%l%T%m%T%n"
    appenders:
      # - type: FileLogAppender
      #   file: root_log.txt
      - type: StdoutLogAppender
  - name: system
    level: DEBUG
    formatter: "%d{%Y-%m-%d %H:%M:%S}%T[%t %N]%T%F%T[%p]%T[%c]%T%f:%l%T%m%T%n"
    appenders:
      # - type: FileLogAppender
      #   file: system_log.txt
      - type: StdoutLogAppender

tcp:
  msg_queue_size: 5
